---
- name: upgrading packs
  apt: upgrade=dist force_apt_get=yes update_cache=yes
  when: upgrade_all

- name: checking rebooting requirement
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no

- name: rebooting server
  reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists

- name: setting clastah versions
  copy:
    content: |
      Package: kubelet kubeadm kubectl
      Pin: version 1.19.7-*
      Pin-Priority: 600

      Package: kubernetes-cni
      Pin: version 0.8.*
      Pin-Priority: 600
    dest: /etc/apt/preferences.d/kube-binaries.pref

- name: adding keys
  apt_key:
    url='{{item.key}}'
  with_items: "{{ clastah_add_packages_keys }}"
  when: clastah_add_packages_keys is defined and not (clastah_add_packages_keys is none or clastah_add_packages_keys | trim == '')
  register: aptnewkeys

- name: adding repo
  apt_repository:
    repo='{{item.repo}}'
  with_items: "{{ clastah_add_packages_repositories }}"
  when: clastah_add_packages_repositories is defined and not (clastahadd_packages_repositories is none or clastah_add_packages_repositories | trim == '')

- name: updating cache
  set_fact:
        clastah_add_packages_cache_valid_time: 0
  when: aptnewkeys.changed

- name: removing packs
  apt:
    name={{ item.name }}
    state=absent
  with_items: "{{ clastah_remove_packages_names }}"
  when: clastah_remove_packages_names is defined and not (clastah_remove_packages_names is none or clastah_remove_packages_names | trim == '')

- name: getting packs
  apt:
    name={{ item.name }}
    state=present
    update_cache=yes
    cache_valid_time={{clastah_add_packages_cache_valid_time}}
  with_items: "{{ clastah_add_packages_names }}"
  when: clastah_add_packages_names is defined and not (clastah_add_packages_names is none or clastah_add_packages_names | trim == '')


