clastah_adding_keys:
- key: https://download.docker.com/linux/debian/gpg
- key: https://packages.cloud.google.com/apt/doc/apt-key.gpg


clastah_adding_repo:
- repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
- repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"


clastah_getting_packs:
- name: apt-transport-https
- name: nfs-kernel-server
- name: containerd.io
- name: docker-ce
- name: kubeadm=1.19.7-*




clastah_removing_packs:
- name:

clastah_modprobe:
  - name: overlay
  - name: br_netfilter

clastah_sysctl:
  - name: net.bridge.bridge-nf-call-iptables
    value: 1
  - name: net.ipv4.ip_forward
    value: 1
  - name: net.bridge.bridge-nf-call-ip6tables
    value: 1

clastah_admin_user:  "vagrant"
clastah_admin_group: "vagrant"